# name: Linters

# on:
#   push:
#     branches:
#       - main
#       - "release/**"
#   pull_request:
#     paths:
#       - .github/workflows/linters.yml
#       - .go-version
#       - .golangci.yml
#       - go.sum
#       - GNUmakefile
#       - internal/**
#       - main.go
#       - tools/**

# jobs:
#   go_mod_download:
#     name: go mod download
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

#       - id: go-version
#         uses: juliangruber/read-file-action@02bbba9876a8f870efd4ad64e3b9088d3fb94d4b # v1.1.6
#         with:
#           path: ./.go-version

#       - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
#         with:
#           # TODO: Replace with go-version-from-file when it is supported
#           # https://github.com/actions/setup-go/pull/62
#           go-version: ${{ steps.go-version.outputs.content }}

#       - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
#         continue-on-error: true
#         id: cache-go-pkg-mod
#         timeout-minutes: 2
#         with:
#           path: ~/go/pkg/mod
#           key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}

#       # Needed to access private repositories. Unfortunately, this cannot be restricted to specific repositories
#       - run: git config --global url."https://${{ secrets.PRIVATE_GOMOD_TOKEN }}:x-oauth-basic@github.com/hashicorp".insteadOf "https://github.com/hashicorp"

#       - if: steps.cache-go-pkg-mod.outputs.cache-hit != 'true' || steps.cache-go-pkg-mod.outcome == 'failure'
#         run: go mod download

#   golangci-lint:
#     needs: [go_mod_download]
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

#       - id: go-version
#         uses: juliangruber/read-file-action@02bbba9876a8f870efd4ad64e3b9088d3fb94d4b # v1.1.6
#         with:
#           path: ./.go-version

#       - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
#         with:
#           # TODO: Replace with go-version-from-file when it is supported
#           # https://github.com/actions/setup-go/pull/62
#           go-version: ${{ steps.go-version.outputs.content }}

#       - name: GOCACHE
#         run: |
#           echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV

#       - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
#         continue-on-error: true
#         timeout-minutes: 2
#         with:
#           # TODO: Replace with supported mechanism when it is supported
#           # https://github.com/actions/setup-go/issues/54
#           path: ${{ env.GOCACHE }}
#           key: ${{ runner.os }}-GOCACHE-${{ hashFiles('go.sum') }}-${{ hashFiles('internal/**') }}

#       - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
#         continue-on-error: true
#         timeout-minutes: 2
#         with:
#           path: ~/go/pkg/mod
#           key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}

#       - run: cd tools && go install github.com/golangci/golangci-lint/cmd/golangci-lint

#       # Needed to access private repositories. Unfortunately, this cannot be restricted to specific repositories
#       - run: git config --global url."https://${{ secrets.PRIVATE_GOMOD_TOKEN }}:x-oauth-basic@github.com/hashicorp".insteadOf "https://github.com/hashicorp"

#       - run: golangci-lint run ./internal/...

#   unit-test:
#     needs: [go_mod_download]
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

#       - id: go-version
#         uses: juliangruber/read-file-action@02bbba9876a8f870efd4ad64e3b9088d3fb94d4b # v1.1.6
#         with:
#           path: ./.go-version

#       - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
#         with:
#           # TODO: Replace with go-version-from-file when it is supported
#           # https://github.com/actions/setup-go/pull/62
#           go-version: ${{ steps.go-version.outputs.content }}

#       - name: GOCACHE
#         run: |
#           echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV

#       - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
#         continue-on-error: true
#         timeout-minutes: 2
#         with:
#           # TODO: Replace with supported mechanism when it is supported
#           # https://github.com/actions/setup-go/issues/54
#           path: ${{ env.GOCACHE }}
#           key: ${{ runner.os }}-GOCACHE-${{ hashFiles('go.sum') }}-${{ hashFiles('internal/**') }}

#       - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
#         continue-on-error: true
#         timeout-minutes: 2
#         with:
#           path: ~/go/pkg/mod
#           key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}

#       # Needed to access private repositories. Unfortunately, this cannot be restricted to specific repositories
#       - run: git config --global url."https://${{ secrets.PRIVATE_GOMOD_TOKEN }}:x-oauth-basic@github.com/hashicorp".insteadOf "https://github.com/hashicorp"

#       - run: make test

#   semgrep:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

#       - name: semgrep
#         uses: returntocorp/semgrep-action@483865da2af626034be23030870fed4bb42371db # v1

#   importlint:
#     needs: [go_mod_download]
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

#       - id: go-version
#         uses: juliangruber/read-file-action@02bbba9876a8f870efd4ad64e3b9088d3fb94d4b # v1.1.6
#         with:
#           path: ./.go-version

#       - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
#         with:
#           # TODO: Replace with go-version-from-file when it is supported
#           # https://github.com/actions/setup-go/pull/62
#           go-version: ${{ steps.go-version.outputs.content }}

#       - name: GOCACHE
#         run: |
#           echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV

#       - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
#         continue-on-error: true
#         timeout-minutes: 2
#         with:
#           # TODO: Replace with supported mechanism when it is supported
#           # https://github.com/actions/setup-go/issues/54
#           path: ${{ env.GOCACHE }}
#           key: ${{ runner.os }}-GOCACHE-${{ hashFiles('go.sum') }}-${{ hashFiles('internal/**') }}

#       - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
#         continue-on-error: true
#         timeout-minutes: 2
#         with:
#           path: ~/go/pkg/mod
#           key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}

#       - run: cd tools && go install github.com/pavius/impi/cmd/impi

#       - run: impi --local . --scheme stdThirdPartyLocal --ignore-generated=true ./...
