name: Pull Request Feed

on:
  pull_request_target:
    types: [opened, closed]

permissions:
  contents: read

env:
  PR_HTML_URL: ${{ github.event.pull_request.html_url }}
  PR_TITLE: ${{ github.event.pull_request.title }}

jobs:
  feed:
    name: Slack Notifications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Community Check
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          sparse-checkout: .github/actions/community_check

      - name: Run Community Check
        id: community_check
        uses: ./.github/actions/community_check
        with:
          user_login: ${{ github.event.pull_request.user.login }}
          maintainers: ${{ secrets.MAINTAINERS }}
          partners: ${{ secrets.PARTNERS }}

      - name: Pull Request Merged
        if: github.event.pull_request.merged
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        env:
          MERGED_BY_URL: ${{ github.event.pull_request.merged_by.html_url }}
          MERGED_BY_LOGIN: ${{ github.event.pull_request.merged_by.login }}
        with:
          webhook: ${{ secrets.FEED_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJSON(format(':merged: [AWSCC] <{0}|{1}> merged <{2}|{3}>', env.MERGED_BY_URL, env.MERGED_BY_LOGIN, env.PR_HTML_URL, env.PR_TITLE)) }}
                  }
                }
              ]
            }

      - name: Maintainer Pull Request Opened
        if: |
          github.event.action == 'opened'
          && steps.community_check.outputs.maintainer == 'true'
          && github.actor != 'dependabot[bot]'
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        env:
          PR_AUTHOR_URL: ${{ github.event.pull_request.user.html_url }}
          PR_AUTHOR_LOGIN: ${{ github.event.pull_request.user.login }}
        with:
          webhook: ${{ secrets.FEED_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJSON(format(':open: [AWSCC] <{0}|{1}> opened <{2}|{3}>', env.PR_AUTHOR_URL, env.PR_AUTHOR_LOGIN, env.PR_HTML_URL, env.PR_TITLE)) }}
                  }
                }
              ]
            }

      - name: Partner Pull Request Opened
        if: |
          github.event.action == 'opened'
          && steps.community_check.outputs.partner == 'true'
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        env:
          PR_AUTHOR_URL: ${{ github.event.pull_request.user.html_url }}
          PR_AUTHOR_LOGIN: ${{ github.event.pull_request.user.login }}
        with:
          webhook: ${{ secrets.FEED_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJSON(format(':open: [AWSCC] :aws: contributor <{0}|{1}> opened <{2}|{3}>', env.PR_AUTHOR_URL, env.PR_AUTHOR_LOGIN, env.PR_HTML_URL, env.PR_TITLE)) }}
                  }
                }
              ]
            }
