# name: Check if tfplugindocs result matches /docs

# on:
#   push:
#     branches:
#       - main
#       - "release/**"
#   pull_request:
#     paths:
#       - .github/workflows/tfplugindocs-check.yml
#       - .go-version
#       - .golangci.yml
#       - go.sum
#       - GNUmakefile
#       - internal/**
#       - main.go
#       - tools/**
#       - docs/**

# jobs:
#   tfplugindocs_check:
#     name: tfplugindocs check
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

#       - id: go-version
#         uses: juliangruber/read-file-action@02bbba9876a8f870efd4ad64e3b9088d3fb94d4b # v1.1.6
#         with:
#           path: ./.go-version

#       - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
#         with:
#           # TODO: Replace with go-version-from-file when it is supported
#           # https://github.com/actions/setup-go/pull/62
#           go-version: ${{ steps.go-version.outputs.content }}

#       - name: GOCACHE
#         run: |
#           echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV

#       - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
#         continue-on-error: true
#         timeout-minutes: 2
#         with:
#           # TODO: Replace with supported mechanism when it is supported
#           # https://github.com/actions/setup-go/issues/54
#           path: ${{ env.GOCACHE }}
#           key: ${{ runner.os }}-GOCACHE-${{ hashFiles('go.sum') }}-${{ hashFiles('internal/**') }}

#       - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
#         continue-on-error: true
#         timeout-minutes: 2
#         with:
#           path: ~/go/pkg/mod
#           key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}

#       - run: |
#           make tools
#           make docs
#           git add -N docs/
#           git diff --exit-code
