# Copyright IBM Corp. 2021, 2026
# "SPDX-License-Identifier: MPL-2.0"

name: Check if tfplugindocs result matches /docs

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .github/workflows/tfplugindocs-check.yml
      - .golangci.yml
      - go.sum
      - GNUmakefile
      - internal/**
      - main.go
      - tools/**
      - docs/**
      - examples/**

jobs:
  tfplugindocs_check:
    name: tfplugindocs check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: tools/go.mod
      - name: GOCACHE
        run: |
          echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV
      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        continue-on-error: true
        timeout-minutes: 2
        with:
          # TODO: Replace with supported mechanism when it is supported
          # https://github.com/actions/setup-go/issues/54
          path: ${{ env.GOCACHE }}
          key: ${{ runner.os }}-GOCACHE-${{ hashFiles('go.sum') }}-${{ hashFiles('internal/**') }}
      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}

      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85
        with:
          terraform_wrapper: false

      - run: |
          make tools
          make docs-fmt
          make docs
          git add -N docs/
          git diff --exit-code
